Code cleanup
GTNewHorizons/Draconic-Evolution pull request #39
Opened 2023-06-13 12:14 UTC by OneEyeMaker

This PR aims to clean up code of multiblocks (and some related things).

### Summary

* Removed countless unnecessary calls of `world.getTileEntity` (Original code makes 3+ calls to get just one TileEntity).
* Removed unnecessary updates of neighbors of neighbor blocks (Yes, neighbors of neighbors).
* Reduced amount of duplicate code.
* Removed stale commented code occurrences.
* Simplified Energy Core structure check.
Removed most repeated checks of the same block.
* Simplified Reactor structure check.
Now Draconium Reactor doesn't attempt to rebuild on every tick with open UI.
* Fixed fuel and output dupe with Draconium Reactor.
* Now sided TileEntities (mainly Reactor parts) use ForgeDirection instead of integers.

2023-06-14 18:29 UTC, wlhlm requested changes
Overall, I have to say excellent work!

But I think using modern Java syntax can help here. Especially for those large switch statements all over the place (no more `break`!).

2023-06-14 18:29 UTC, wlhlm commented on src/main/java/com/brandon3055/draconicevolution/client/gui/GUIPlayerDetector.java
> +    private static final ResourceLocation Texture = new ResourceLocation(
Why use upper case here for first char in variable name?

2023-06-14 18:29 UTC, wlhlm commented on src/main/java/com/brandon3055/draconicevolution/client/gui/GuiHandler.java
> +                break;
I think we should enable modern Java syntax (via Jabel) and use the new switch statement across the mod, like
```java
switch () {
    case ... -> { }
}
```

2023-06-14 18:29 UTC, wlhlm commented on src/main/java/com/brandon3055/draconicevolution/common/blocks/ParticleGenerator.java
> +        if (tile instanceof TileEnergyStorageCore) {
We can use the new java syntax here (if we enable Jabel):
```java
if (tile instanceof TileEnergyStorageCore core) {
    // ...
}
```
This applies in many other places in this PR as well.

2023-06-14 18:29 UTC, wlhlm commented on src/main/java/com/brandon3055/draconicevolution/common/tileentities/TilePlayerDetector.java
> +        }
`value = Math.max(MINIMUM_RANGE, Math.min(MAXIMUM_RANGE, value));`

2023-06-14 18:29 UTC, wlhlm commented on src/main/java/com/brandon3055/draconicevolution/common/tileentities/multiblocktiles/reactor/TileReactorCore.java
> +import java.util.*;
Please avoid wildcard imports

2023-06-14 18:29 UTC, wlhlm commented on src/main/java/com/brandon3055/draconicevolution/common/tileentities/multiblocktiles/reactor/TileReactorCore.java
> +                fieldCharge = maxFieldCharge;
I kinda like using `Math.min()` for this.

2023-06-14 18:29 UTC, wlhlm commented on src/main/java/com/brandon3055/draconicevolution/client/gui/GUIParticleGenerator.java
> +                settingsSaver = new GuiButton(127, posX + 105, posY + 19 + 7 * 22, 102, 20, "Take note of values"));
I think we should make all those button labels translatable.

2023-06-14 18:29 UTC, wlhlm commented on src/main/java/com/brandon3055/draconicevolution/client/gui/GUIParticleGenerator.java
> +        buttonList.add(previousPage = new GuiButton(100, posX - 47, posY + 177, 47, 20, "<==="));
Those arrows are pretty ugly. I think we should use just `<`/`>` like in NEI for switching between pages.

2023-06-14 22:55 UTC, OneEyeMaker commented on src/main/java/com/brandon3055/draconicevolution/common/tileentities/TilePlayerDetector.java
> +        }
The idea is not to clamp, but to cycle value. When value reaches maximum it becomes minimum value. I. e. 9 -> 10 -> 1 -> 2 (and vice versa: 2 -> 1 -> 10 -> 9).

But I can change it anyway if clamping is more preferable.

2023-06-14 22:56 UTC, wlhlm commented on src/main/java/com/brandon3055/draconicevolution/common/tileentities/TilePlayerDetector.java
> +        }
No, I've missed that. Cycling makes sense.

2023-06-15 15:10 UTC, wlhlm requested changes

2023-06-15 15:10 UTC, wlhlm commented on src/main/java/com/brandon3055/draconicevolution/client/render/tile/RenderTileReactorEnergyInjector.java
> +        switch (injector.facing) {
Update switch syntax.

2023-06-15 15:10 UTC, wlhlm commented on src/main/java/com/brandon3055/draconicevolution/client/render/tile/RenderTileReactorStabilizer.java
> +        switch (stabilizer.facing) {
switch syntax

2023-06-15 16:02 UTC, wlhlm approved these changes

2023-06-15 17:09 UTC, merged